[project]
name = "anticipator"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["click"]

[project.scripts]
anticipator = "cli.src.cli:main"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"